## Contexte et Problématique

1- Contexte du problème

L’agriculture en Afrique de l’Ouest est fortement influencée par des facteurs climatiques, pédologiques et socio-économiques. L’objectif de ce projet est de construire un modèle capable de prédire le rendement agricole à partir de données multi-sources (FAOSTAT, météo et sol).

2- Problème ML

Il s’agit d’un problème de régression visant à prédire le rendement agricole (yield) en fonction des conditions environnementales et agricoles.

3- Variables utilisées

Variables explicatives :
température moyenne
précipitations
pH du sol
matière organique
type de culture
Variable cible :
rendement agricole (yield)

# Données

#### Chargement des données

In [1]:
import pandas as pd

faostat_df = pd.read_csv("../data/raw/faostat.csv")
meteo_df = pd.read_csv("../data/raw/meteo.csv")
soil_df = pd.read_csv("../data/raw/soil.csv")

#### Vérifier la structure

In [2]:
faostat_df.head()

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,QCL,Crops and livestock products,204,Benin,5312,Area harvested,1520.01,"Cassava, fresh",2000,2000,ha,219404.0,A,Official figure,NaN
1,QCL,Crops and livestock products,204,Benin,5412,Yield,1520.01,"Cassava, fresh",2000,2000,kg/ha,10711.8,A,Official figure,NaN
2,QCL,Crops and livestock products,204,Benin,5510,Production,1520.01,"Cassava, fresh",2000,2000,t,2350210.0,A,Official figure,NaN
3,QCL,Crops and livestock products,204,Benin,5312,Area harvested,1520.01,"Cassava, fresh",2001,2001,ha,240048.0,A,Official figure,NaN
4,QCL,Crops and livestock products,204,Benin,5412,Yield,1520.01,"Cassava, fresh",2001,2001,kg/ha,11262.2,A,Official figure,NaN

In [3]:
meteo_df.head()

  country  year  avg_temp_c  total_precip_mm
0   Benin  2000   26.907377           1298.6
1   Benin  2001   26.925205            984.6
2   Benin  2002   27.001096           1332.9
3   Benin  2003   27.223288           1153.4
4   Benin  2004   26.996721            983.2

In [4]:
soil_df.head()

   country  soil_ph  organic_matter  clay_pct
0    Benin      6.2             242       167
1  Senegal      6.6              77       195
2    Ghana      6.2             247       273
3  Nigeria      5.8             294       211
4     Mali      7.8              69       310

#### Harmoniser les données pour les fusionner

In [5]:
faostat_df = faostat_df.rename(columns={
    "Area": "country",
    "Year": "year"
})

In [6]:
# Nettoyage des espaces
faostat_df["country"] = faostat_df["country"].str.strip()
meteo_df["country"] = meteo_df["country"].str.strip()
soil_df["country"] = soil_df["country"].str.strip()

#### Jointure

In [7]:
# faostat + météo 

df_1 = faostat_df.merge(
    meteo_df,
    on=["country", "year"],
    how="left"
)

In [8]:
# + sol
df= df_1.merge(
    soil_df,
    on="country",
    how="left"
)

In [9]:
df.to_csv("../data/processed/dataset_final.csv", index=False)